hw accordion
js-tasks-ru/htmlcss-20230411_sa pull request #5
Opened 2023-04-24 14:09 UTC by Su8184

2023-04-24 14:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 20:15 UTC, GSemikozov requested changes

2023-04-24 20:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
лишнее ограничение

2023-04-24 20:15 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
можно еще общие паддинги указать именно на этом уровне

2023-04-24 20:21 UTC, Su8184 commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
тогда же "кликабельная" часть станет меньше (на паддингах не будет действия открыть аккордеон)

2023-04-24 20:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 21:08 UTC, GSemikozov approved these changes, later dismissed

2023-04-24 21:08 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-04-24 21:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 21:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-24 21:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 11:55 UTC, GSemikozov approved these changes

2023-04-25 11:56 UTC, merged