add tooltip
js-tasks-ru/htmlcss-20230411_sa pull request #9
Opened 2023-05-12 02:44 UTC by Su8184

2023-05-12 02:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-12 13:26 UTC, GSemikozov requested changes

2023-05-12 13:26 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__message-box_up {
у нас только такой вариант и возможен, так что - перенесем в tooltip__message-box )

2023-05-12 15:34 UTC, Su8184 commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__message-box_up {
done

2023-05-12 15:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-12 15:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-16 07:40 UTC, GSemikozov approved these changes

2023-05-16 07:40 UTC, merged